### ISSUE TITLE
numpad

### ISSUE THREAD

**Issue by hughes** [peterklijn/hammerspoon-shiftit#12]
Is the numpad supposed to work with any of the hotkeys? It doesn't seem to.

**Comment by peterklijn** [comment]
Hi @hughes,

That's correct, in Hammerspoon regular numbers and numbed numbers are defined separately: https://www.hammerspoon.org/docs/hs.keycodes.html#map

I'm not sure if specifying your preferred keys in the overrides will work for you? https://github.com/peterklijn/hammerspoon-shiftit#overriding-key-mappings

If not, feel free to make a PR :)

**Comment by hughes** [comment]
Confirmed the pad works using the Hammerspoon numpad key names.
