### ISSUE TITLE
Support for multiple arrow keys?

### ISSUE THREAD

**Issue by stefanlasiewski** [peterklijn/hammerspoon-shiftit#14]
I was curious if it's possible to bind an action to two keys instead of one. This was something I've been doing with [Miro Windows Manager](https://github.com/miromannino/miro-windows-manager).

For example:
* If I have a window on the right hand side and hit the `DOWN`+`LEFT` arrow keys simultaneously, the window is moved to the lower left-hand corner of the window.

* if I have a window in the lower-left corner but I resized it manually, then hit the `UP`+`DOWN` arrow keys simultaneously, the window will be on the left side but is now tall. If I hit those same arrow keys again it returns to it's original size.

Is this possible with Hammerspoon Shifit?

Here are some example keybindings:

```
local hyper = {'ctrl', 'alt', 'cmd'}
hs.window.animationDuration = 0.1
spoon.MiroWindowsManager:bindHotkeys({
  fullscreen  = {hyper, 'm'},
  up          = {hyper, 'up'},
  right       = {hyper, 'right'},
  down        = {hyper, 'down'},
  left        = {hyper, 'left'},
  upleft      = {hyper, 'up', 'left'},
  upright     = {hyper, 'up', 'right' },
  botleft     = {hyper, 'down', 'left' },
  botright    = {hyper, 'down', 'right' },
})
```

**Comment by peterklijn** [comment]
Hi @stefanlasiewski,

As far as I can see, this is not possible. 

I use the Hammerspoon `hotkey.bind(...)` method, which only allows for a single key ([docs](https://www.hammerspoon.org/docs/hs.hotkey.html#bind)). 
The list of all available keys can be found [here](https://www.hammerspoon.org/docs/hs.keycodes.html#map), there seems to be no combination of keys.

You can consider making an issue in [Hammerspoon](https://github.com/Hammerspoon/hammerspoon/issues), after which is would be possible to add it here as well.
