### ISSUE TITLE
Set window in % of screen

### ISSUE THREAD

**Issue by DamianHofy** [peterklijn/hammerspoon-shiftit#17]
I would have main window for (for example) 80% from the left and a second window for 20% from the right instead 50-50 

How can I achieve that?

**Comment by peterklijn** [comment]
Hi @DamianHofy,

Sorry for the late response. I just released a new version of Hammerspoon-ShiftIt, which supports multiple window cycle sizes. 
I think you can configure it to solve your use-case, have a look here: https://github.com/peterklijn/hammerspoon-shiftit#configure-multiple-window-cycle-sizes

You need to download the latest version to use it: https://github.com/peterklijn/hammerspoon-shiftit/releases/latest/download/ShiftIt.spoon.zip
