### ISSUE TITLE
Installing via SpoonInstall does not work

### ISSUE THREAD

**Issue by colinsullivan** [peterklijn/hammerspoon-shiftit#2]
The error console just shows the entire GitHub HTML but maybe this is the relevant bit?

```
<meta name="selected-link" value="/peterklijn/hammerspoon-shiftit.git/raw/master/docs/docs.json" data-pjax-transient>
```

**Comment by peterklijn** [comment]
Thanks for reporting @colinsullivan, I was able to reproduce the problem.

I believe it's fixed now, I've updated [the readme](https://github.com/peterklijn/hammerspoon-shiftit#spooninstall) with instructions.

Would you mind trying again? And if it doesn't work, would you mind sharing your `init.lua`?

**Comment by peterklijn** [comment]
Closing due to no reply.
