### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arkal** [peterklijn/hammerspoon-shiftit#20]
Hey there. I love using this software and would like to use it on my work laptop but can't till IT sees that it is legally OK to do so. Can you please add a license to the repo?

**Comment by peterklijn** [comment]
Hi @arkal,
Thanks for reaching out, I've added [a licence](https://github.com/peterklijn/hammerspoon-shiftit/blob/master/LICENSE.md).
Enjoy!

**Comment by arkal** [comment]
Thanks a bunch! Shiftit (and subsequently hammerspoon-shiftit) have made multiple monitor setups infinitely easier to use.
