### ISSUE TITLE
support for multipleActionsCycleWindowSizes

### ISSUE THREAD

**Issue by mitchellirvin** [peterklijn/hammerspoon-shiftit#22]
hello!

is there a way to enable the multipleActionsCycleWindowSizes flag? previously it was able to be set via command line:
`defaults write org.shiftitapp.ShiftIt multipleActionsCycleWindowSizes YES`, but that doesn't appear to work with hammerspoon.

original shiftit issue: https://github.com/fikovnik/ShiftIt/issues/303
original shiftit docs: https://github.com/fikovnik/ShiftIt#how-do-i-turn-onoff-windows-cycling-sizes-with-multiple-hotkey-presses

thanks so much!

**Comment by peterklijn** [comment]
Hi @mitchellirvin,

Thanks for submitting an issue.

I'm actually working on that and hope to finish it soon.

You can follow the PR here, and get notified when it's merged:

https://github.com/peterklijn/hammerspoon-shiftit/issues/21

Cheers,
Peter

**Comment by peterklijn** [comment]
Hi @mitchellirvin,

The new version of Hammerspoon-ShiftIt is released and supports multiple cycling window sizes!

Please download the latest spoon (https://github.com/peterklijn/hammerspoon-shiftit/releases/latest) and config it by following the documentation in the readme (https://github.com/peterklijn/hammerspoon-shiftit#configure-multiple-window-cycle-sizes).

**Comment by mitchellirvin** [comment]
@peterklijn thanks so much for such a quick response and release! This is awesome and I really appreciate it.
