### ISSUE TITLE
Support 1/3rds?

### ISSUE THREAD

**Issue by concretevitamin** [peterklijn/hammerspoon-shiftit#27]
In ShiftIt, `ctrl + option + command + <left>` twice would put a window at 1/3rd of the screen. Can hammerspoon-shiftit support it too?

**Comment by peterklijn** [comment]
Hi @concretevitamin,
It already does! It was added a few months ago ;)
Make sure you download the latest version, and follow [the readme](https://github.com/peterklijn/hammerspoon-shiftit#configure-multiple-window-cycle-sizes)
