### ISSUE TITLE
No longer able to position Google Chrome

### ISSUE THREAD

**Issue by austingreendev** [peterklijn/hammerspoon-shiftit#30]
With the latest Google Chrome release `Version 110.0.5481.177 (Official Build) (arm64)` I'm no longer able to position the chrome window. It's still working for other browser and windows.

Did something change recently?

**Comment by peterklijn** [comment]
Hi Austin,

I'm running the exact same Chrome version, and for me it works 😕.
Can you make sure you run the latest Hammerspoon, and perhaps give your Mac a restart? 

If that didn't help, do you see logs in the Hammerspoon console when you try to move the window?

**Comment by austingreendev** [comment]
A restart didn't seem to help, but after toggling the accessibility control for Hammerspoon I was able to get this working again. It must have been transient from the Chrome install.

Thanks for taking a look.
