### ISSUE TITLE
Can't bind to or use side numberpad

### ISSUE THREAD

**Issue by lauracoombs07** [peterklijn/hammerspoon-shiftit#6]
Using an external keyboard with my macbook, side numbers don't work and can't be bound. Is there a workaround? Thanks

**Comment by peterklijn** [comment]
Thanks for submitting an issue @lauracoombs07,

Are you referring to the 'numlock' numbers? I'm currently on vacation so it will be a week before I can verify :)

**Comment by peterklijn** [comment]
Hi @lauracoombs07,

You can bind numberpad keys by using the values `pad0` to `pad9`.

A full list of all keys can be found [here](https://www.hammerspoon.org/docs/hs.keycodes.html#map).

**Comment by lauracoombs07** [comment]
Works perfectly! Thank you!
