### ISSUE TITLE
Snap to sixth of screen

### ISSUE THREAD

**Issue by winni2k** [peterklijn/hammerspoon-shiftit#8]
When using an ultra-wide screen then quarters of the screen are a bit too wide for my liking. Is there a way to implement a grid of six or more equal-size rectangles to which one can snap a window?

**Comment by peterklijn** [comment]
Hi Winni,

That's a good idea! There's a few concerns that come to mind.

1. I think the default behaviour should stay as close to ShiftIt as possible, so perhaps it can be made configurable.

    Perhaps one can configure a grid, like number of rows & number of columns, which defaults to 4.

2. I assume you use the `ctrl(^) + alt(⌥) + cmd(⌘) + <arrow>` for snapping, how would you snap to the middle columns?

```
ctrl(^) + alt(⌥) + cmd(⌘) + left would do:
+---+---+---+
|XXX|   |   |
+XXX+---+---+
|XXX|   |   |
+---+---+---+

ctrl(^) + alt(⌥) + cmd(⌘) + up would do:
+---+---+---+
|XXX|XXX|XXX|
+---+---+---+
|   |   |   |
+---+---+---+

But what about:
+---+---+---+
|   |XXX|   |
+---+XXX+---+
|   |XXX|   |
+---+---+---+

Or about bigger grids:
+---+---+---+---+   +---+---+---+---+
|   |XXX|   |   |   |   |   |   |   |
+---+XXX+---+---+   +---+---+---+---+
|   |XXX|   |   |   |XXXXXXXXXXXXXXX|   etc..
+---+XXX+---+---+   +---+---+---+---+
|   |XXX|   |   |   |   |   |   |   |
+---+---+---+---+   +---+---+---+---+
```

3. I guess the `cmd + option + ctrl + <number>` would just increment, but also here you'd run out of numbers:

```
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 | 5 | 6 |
+---+---+---+

+---+---+---+---+
| 1 | 2 | 3 | 4 |
+---+---+---+---+
| 5 | 6 | 7 | 8 |
+---+---+---+---+
| 9 |   |   |   |
+---+---+---+---+
```

What do you think?

**Comment by winni2k** [comment]
What I like about ShiftIt is that it is simple and does (almost) everything I need, but not much more. I think implementing 3. would solve my issue sufficiently for me to move on with my life. Regarding 3.: If you run out of numbers, then you could always use letters as well...

2. is an interesting consideration, but I don't think that solving 2. would lead to a design that is easy to use 🤷

**Comment by peterklijn** [comment]
Hi @winni2k,

The new version of Hammerspoon-ShiftIt is released and supports multiple cycling window sizes! Perhaps this helps with your use case.

You can download the latest spoon (https://github.com/peterklijn/hammerspoon-shiftit/releases/latest) and config it by following the documentation in the readme (https://github.com/peterklijn/hammerspoon-shiftit#configure-multiple-window-cycle-sizes).

**Comment by winni2k** [comment]
Excellent! Thanks!
